from pathlib import Path
from zoneinfo import ZoneInfo


# Data Processing Assistance
BASE_DIR = Path(__file__).resolve().parents[1]
DATA_ROOT = BASE_DIR.parent / "Exam Data" / "open-data" / "data"
ITERATION_ID = 743
FREIBURG_NAME = "SC Freiburg"
BERLIN_TZ = ZoneInfo("Europe/Berlin")

KPI_RED_CARD = 47
KPI_SHOT_XG = 82
KPI_SUCCESSFUL_PASSES = 90
KPI_UNSUCCESSFUL_PASSES = 91
KPI_SHOTS = 100
KPI_NEUTRAL_PASSES = 1431
KPI_SHOTS_ON_TARGET = 1515
KPI_YELLOW_CARD = 1637
KPI_SECOND_YELLOW_CARD = 1638

KPI_POSTSHOT_XG = 1401
KPI_PXT_PASS = 1404
KPI_PXT_DRIBBLE = 1405
KPI_PXT_SETPIECE = 1406
KPI_PXT_BLOCK = 1407
KPI_PXT_SHOT = 1408
KPI_PXT_BALL_WIN = 1409
KPI_PXT_FOUL = 1410
KPI_PXT_NO_VIDEO = 1411
KPI_PXT_REC = 1412
KPI_OPP_PXT_PASS = 1413
KPI_OPP_PXT_DRIBBLE = 1414
KPI_OPP_PXT_SETPIECE = 1415
KPI_OPP_PXT_BLOCK = 1416
KPI_OPP_PXT_SHOT = 1417
KPI_OPP_PXT_BALL_WIN = 1418
KPI_OPP_PXT_FOUL = 1419
KPI_OPP_PXT_NO_VIDEO = 1420
KPI_OPP_PXT_BALL_LOSS = 1421
KPI_PXT_PASSIVE = 1531
KPI_PXT_OTHER = 1532
KPI_PXT_FOULED = 1533
KPI_PXT_ATTACK = 1633
KPI_PXT_DEFEND = 1634
KPI_DEF_PXT_ATTACK = 1635
KPI_DEF_PXT_DEFEND = 1636
KPI_DEF_PXT_PASS = 1522
KPI_DEF_PXT_DRIBBLE = 1523
KPI_DEF_PXT_SETPIECE = 1524
KPI_DEF_PXT_BLOCK = 1525
KPI_DEF_PXT_SHOT = 1526
KPI_DEF_PXT_BALL_WIN = 1527
KPI_DEF_PXT_ACTIVE = 1534

# These seven KPIs belong to the player tagged on the source event. They are
# useful for action maps, but they are not Impect's complete team PxT total.
TAGGED_ACTION_PXT_KPIS = {
    KPI_PXT_PASS: "Pass",
    KPI_PXT_DRIBBLE: "Dribble",
    KPI_PXT_SETPIECE: "Set Piece",
    KPI_PXT_BLOCK: "Block",
    KPI_PXT_SHOT: "Shot",
    KPI_PXT_BALL_WIN: "Ball Win",
    KPI_PXT_FOUL: "Foul",
}

# Player evaluation also keeps responsibility-based passive PxT and threat
# earned by being fouled. The PDF only recommends excluding no-video/other PxT.
PLAYER_ATTRIBUTABLE_PXT_KPIS = {
    **TAGGED_ACTION_PXT_KPIS,
    KPI_PXT_PASSIVE: "Passive",
    KPI_PXT_FOULED: "Fouled",
}
